apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-app
  labels:
    app: hotstar-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotstar-app
  template:
    metadata:
      labels:
        app: hotstar-app
    spec:
      containers:
      - name: hotstar-app
        image: dockerperala/hotstar
        ports:
        - containerPort: 8080

